apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  labels:
    cloud.googleapis.com/location: europe-west1
  annotations:
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/ingress: all
    run.googleapis.com/maxScale: '1'
    run.googleapis.com/minScale: '0'

spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: ${SERVICE_ACCOUNT_NAME}
      containers:
      - image: ${IMAGE_NAME}
        ports:
        - containerPort: 8000
        env: []
        args:
        - ${BUCKET_NAME}
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8000
  traffic:
  - percent: 100
    latestRevision: true
